// Grant Intelligence™
// Module 02 — Grant Readiness Assessment
// v1 client for the two-function Supabase architecture:
//
//   module02.js
//      -> run-module02   (starts/records the Dify workflow)
//      -> check-module02 (checks status and finalizes/saves result)

const $ = (id) => document.getElementById(id);

let session = null;
let profile = null;
let project = null;

let pollTimer = null;
let processingStartedAt = null;
let activeRunId = null;

const POLL_INTERVAL_MS = 10000;

const DEMO_REPORT = `# GRANT INTELLIGENCE™

## Module 02 – Grant Readiness Assessment (DEMO SAMPLE)

This is demonstration content. It was not generated by Dify and does not describe the signed-in user.

Overall Grant Readiness Score: 58/100
Readiness Level: Developing
Assessment Confidence: Moderate

This sample demonstrates the presentation format only.`;

function status(message, kind = "") {
  const box = $("runStatus");
  if (!box) return;
  box.textContent = message;
  box.className = "statusbox " + kind;
}

function setRunButtonProcessing(isProcessing) {
  const button = $("runBtn");
  if (!button) return;
  button.disabled = isProcessing;
  button.textContent = isProcessing
    ? "Module 02 Processing…"
    : "Run Module 02";
}

function showReport(text) {
  const report = $("report");
  if (!report) return;
  report.textContent =
    text ||
    "Module 02 completed, but no Grant Readiness Report was returned.";
}

function elapsedMessage() {
  if (!processingStartedAt) return "Assessment has started.";

  const seconds = Math.max(
    0,
    Math.floor((Date.now() - processingStartedAt) / 1000)
  );

  if (seconds < 60) return "Assessment has started.";

  const minutes = Math.floor(seconds / 60);
  return minutes === 1
    ? "Assessment has been running for about 1 minute."
    : `Assessment has been running for about ${minutes} minutes.`;
}

function showProcessingStatus(extra = "") {
  const optional = extra ? `\n${extra}` : "";

  status(
    "Evaluating your grant readiness…\n\n" +
      "✓ Your completed Module 01 Organization Intelligence Report has been retrieved.\n" +
      "✓ Secure AI assessment has been started.\n" +
      "⏳ Your Grant Readiness Assessment is being prepared.\n\n" +
      elapsedMessage() +
      optional +
      "\n\nYou may leave this page and return later. " +
      "Your results will remain associated with this project.",
    "processing"
  );

  setRunButtonProcessing(true);
}

function stopPolling() {
  if (pollTimer) {
    clearInterval(pollTimer);
    pollTimer = null;
  }
}

function rememberRunId(value) {
  if (!value || !project) return;

  activeRunId = String(value);
  localStorage.setItem(
    `giModule02RunId:${project.id}`,
    activeRunId
  );
}

function restoreRunId() {
  if (!project) return null;

  const value = localStorage.getItem(
    `giModule02RunId:${project.id}`
  );

  if (value) activeRunId = value;
  return activeRunId;
}

function forgetRunId() {
  if (project) {
    localStorage.removeItem(
      `giModule02RunId:${project.id}`
    );
  }
  activeRunId = null;
}

function extractRunId(data) {
  return (
    data?.workflow_run_id ||
    data?.dify_run_id ||
    data?.run_id ||
    data?.module_result?.dify_run_id ||
    data?.data?.workflow_run_id ||
    data?.data?.id ||
    null
  );
}

function normalizeStatus(data) {
  const raw =
    data?.status ||
    data?.module_result?.status ||
    data?.data?.status ||
    data?.dify_status ||
    "";

  const value = String(raw).toLowerCase();

  if (
    ["running", "processing", "started", "queued", "pending", "starting"].includes(value)
  ) {
    return "running";
  }

  if (
    ["completed", "complete", "succeeded", "success", "finished"].includes(value)
  ) {
    return "completed";
  }

  if (
    ["failed", "error", "stopped", "cancelled", "canceled", "partial-succeeded"].includes(value)
  ) {
    return "failed";
  }

  return value;
}

function extractReport(data) {
  return (
    data?.report_text ||
    data?.module_result?.report_text ||
    data?.report ||
    data?.outputs?.grantReadinessReport ||
    data?.data?.outputs?.grantReadinessReport ||
    data?.grantReadinessReport ||
    ""
  );
}

function extractError(data) {
  const possible =
    data?.error ||
    data?.message ||
    data?.dify_error ||
    data?.module_result?.output_data?.dify_error ||
    data?.module_result?.output_data?.background_error ||
    data?.output_data?.dify_error ||
    data?.output_data?.background_error ||
    data?.data?.error;

  if (!possible) {
    return "Module 02 could not be completed.";
  }

  return typeof possible === "string"
    ? possible
    : JSON.stringify(possible);
}

async function getSavedModule02() {
  if (!project) return null;

  const { data, error } = await giSupabase
    .from("module_results")
    .select("*")
    .eq("project_id", project.id)
    .eq("module_number", 2)
    .maybeSingle();

  if (error) throw error;
  return data;
}

function renderSavedResult(saved) {
  if (!saved) return false;

  if (saved.dify_run_id) {
    rememberRunId(saved.dify_run_id);
  }

  if (saved.status === "completed" && saved.report_text) {
    stopPolling();
    forgetRunId();
    showReport(saved.report_text);
    setRunButtonProcessing(false);

    status(
      "✓ Module 02 complete.\n\n" +
        "Your Grant Readiness Assessment has been generated and saved to your Grant Intelligence account.",
      "ok"
    );

    return true;
  }

  if (saved.status === "running") {
    if (saved.started_at) {
      processingStartedAt =
        new Date(saved.started_at).getTime();
    }
    showProcessingStatus();
    return true;
  }

  if (saved.status === "failed") {
    stopPolling();
    setRunButtonProcessing(false);

    const message =
      saved.output_data?.dify_error ||
      saved.output_data?.background_error ||
      saved.output_data?.error ||
      "The previous Module 02 attempt did not complete.";

    status(
      "The previous Module 02 attempt did not complete.\n\n" +
        (typeof message === "string"
          ? message
          : JSON.stringify(message)) +
        "\n\nYour earlier module results are still saved. You may run Module 02 again.",
      "bad"
    );

    return true;
  }

  return false;
}

async function invokeCheckModule02() {
  if (!project) return;

  const checkBody = {
    project_id: project.id
  };

  if (activeRunId) {
    checkBody.workflow_run_id = activeRunId;
    checkBody.dify_run_id = activeRunId;
    checkBody.run_id = activeRunId;
  }

  const { data, error } =
    await giSupabase.functions.invoke(
      "check-module02",
      { body: checkBody }
    );

  if (error) {
    console.warn("check-module02 invocation failed:", error);

    const saved = await getSavedModule02();
    if (saved) renderSavedResult(saved);
    return;
  }

  const newRunId = extractRunId(data);
  if (newRunId) rememberRunId(newRunId);

  const state = normalizeStatus(data);

  if (state === "completed") {
    let report = extractReport(data);

    const saved = await getSavedModule02();
    if (saved?.report_text) report = saved.report_text;

    stopPolling();
    forgetRunId();
    setRunButtonProcessing(false);
    showReport(report);

    status(
      "✓ Module 02 complete.\n\n" +
        "Your Grant Readiness Assessment has been generated and saved to your Grant Intelligence account.",
      "ok"
    );
    return;
  }

  if (state === "failed") {
    stopPolling();
    setRunButtonProcessing(false);

    status(
      "Module 02 could not be completed.\n\n" +
        extractError(data) +
        "\n\nYour previous module information is still safely stored.",
      "bad"
    );
    return;
  }

  const saved = await getSavedModule02();

  if (saved?.status === "completed" && saved.report_text) {
    renderSavedResult(saved);
    return;
  }

  if (saved?.status === "failed") {
    renderSavedResult(saved);
    return;
  }

  showProcessingStatus(
    state && state !== "running"
      ? `Current processing status: ${state}`
      : ""
  );
}

function startPolling() {
  stopPolling();

  invokeCheckModule02().catch((error) => {
    console.error("Initial check-module02 error:", error);
  });

  pollTimer = setInterval(() => {
    invokeCheckModule02().catch((error) => {
      console.error("check-module02 polling error:", error);
    });
  }, POLL_INTERVAL_MS);
}

async function load() {
  session = await GI.requireSession("module02.html");
  if (!session) return;

  profile = await GI.getProfile();

  if (
    !profile ||
    !["demo", "realtest", "paid", "admin"].includes(
      profile.access_level
    )
  ) {
    location.replace("unlock.html");
    return;
  }

  $("modePill").textContent =
    profile.access_level === "demo"
      ? "DEMO • NO DIFY"
      : profile.access_level === "realtest"
      ? "REAL TEST • DIFY"
      : profile.access_level === "paid"
      ? "PAID • DIFY"
      : "ADMIN";

  const projectId =
    localStorage.getItem("giCurrentProjectId");

  if (!projectId) {
    $("projectInfo").textContent =
      "No current project. Complete Module 00 first.";
    $("runBtn").disabled = true;
    return;
  }

  const { data, error } = await giSupabase
    .from("projects")
    .select("*")
    .eq("id", projectId)
    .single();

  if (error) throw error;

  project = data;
  restoreRunId();

  $("projectInfo").innerHTML =
    `<strong>${project.project_name}</strong><br>` +
    `${project.organization_name || "No organization name yet"}<br>` +
    `Stage: ${project.project_stage || "Not Found"}<br>` +
    `Preliminary Readiness: ${project.readiness_score ?? "Not Found"}`;

  const { data: module01, error: module01Error } =
    await giSupabase
      .from("module_results")
      .select("status,report_text")
      .eq("project_id", project.id)
      .eq("module_number", 1)
      .maybeSingle();

  if (module01Error) throw module01Error;

  if (
    !module01 ||
    module01.status !== "completed" ||
    !module01.report_text
  ) {
    status(
      "Module 01 must be completed before Module 02 can begin.",
      "bad"
    );
    $("runBtn").disabled = true;
    return;
  }

  const saved = await getSavedModule02();

  if (saved?.status === "completed" && saved.report_text) {
    renderSavedResult(saved);
    return;
  }

  if (saved?.status === "running") {
    renderSavedResult(saved);
    startPolling();
    return;
  }

  if (saved?.status === "failed") {
    renderSavedResult(saved);
    return;
  }

  if (activeRunId) {
    processingStartedAt = Date.now();
    showProcessingStatus("Reconnecting to your existing Module 02 run…");
    startPolling();
    return;
  }

  status(
    "Module 01 is complete. Ready to generate your Grant Readiness Assessment."
  );
  setRunButtonProcessing(false);
}

async function runDemo() {
  status(
    "Demo mode: loading sample Grant Readiness Assessment. No Dify credits are used."
  );

  const { error } = await giSupabase
    .from("module_results")
    .upsert(
      {
        user_id: session.user.id,
        project_id: project.id,
        module_number: 2,
        module_name: "Grant Readiness Assessment",
        status: "completed",
        report_text: DEMO_REPORT,
        output_data: {
          sample: true,
          source: "static_demo"
        },
        completed_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      {
        onConflict: "project_id,module_number"
      }
    );

  if (error) throw error;

  showReport(DEMO_REPORT);
  setRunButtonProcessing(false);

  status(
    "✓ Demo Module 02 completed and saved to Supabase. Dify was not called.",
    "ok"
  );
}

async function runModule02() {
  try {
    if (!project) return;

    setRunButtonProcessing(true);

    if (profile.access_level === "demo") {
      await runDemo();
      return;
    }

    const savedBeforeStart = await getSavedModule02();

    if (savedBeforeStart?.status === "running") {
      renderSavedResult(savedBeforeStart);
      startPolling();
      return;
    }

    processingStartedAt = Date.now();
    showProcessingStatus("Starting secure Module 02 workflow…");

    const { data, error } =
      await giSupabase.functions.invoke(
        "run-module02",
        {
          body: {
            project_id: project.id,
            additionalReadinessNotes: ""
          }
        }
      );

    if (error) throw error;
    if (data?.error) throw new Error(extractError(data));

    const runId = extractRunId(data);
    if (runId) rememberRunId(runId);

    const state = normalizeStatus(data);

    if (
      state === "running" ||
      data?.accepted === true ||
      data?.success === true
    ) {
      showProcessingStatus();
      startPolling();
      return;
    }

    if (state === "completed") {
      await invokeCheckModule02();
      return;
    }

    if (state === "failed") {
      throw new Error(extractError(data));
    }

    if (activeRunId) {
      showProcessingStatus();
      startPolling();
      return;
    }

    throw new Error(
      "run-module02 did not return a recognizable launch status or workflow run ID."
    );
  } catch (error) {
    console.error("Module 02 launcher error:", error);

    stopPolling();
    setRunButtonProcessing(false);

    status(
      "Unable to start Module 02.\n\n" +
        (error?.message || String(error)),
      "bad"
    );
  }
}

function attachModule02Events() {
  const button = $("runBtn");

  if (!button) {
    console.error("Run Module 02 button was not found.");
    return;
  }

  button.addEventListener("click", runModule02);
}

document.addEventListener(
  "DOMContentLoaded",
  async () => {
    try {
      attachModule02Events();
      await load();
    } catch (error) {
      console.error("Unable to load Module 02:", error);

      status(
        "Unable to load Module 02: " +
          (error?.message || String(error)),
        "bad"
      );
    }
  }
);

window.addEventListener("beforeunload", stopPolling);
