// Grant Intelligence™
// Module 01 — Organization Intelligence
// Async website controller
//
// Website -> run-module01 launcher
//         -> immediate Processing status
//         -> polls Supabase module_results
//         -> displays report when completed

const $ = (id) => document.getElementById(id);

let session = null;
let profile = null;
let project = null;

let pollTimer = null;
let processingStartedAt = null;

const DEMO_REPORT = `# GRANT INTELLIGENCE™

## Module 01 – Organization Intelligence (DEMO SAMPLE)

This is demonstration content. It was not generated by Dify and does not describe the signed-in user.

Organization Stage: Planning
Mission Clarity: Developing
Program Definition: Preliminary
Governance: Development Required
Financial Infrastructure: Development Required

Key Strengths:
• Clear community-oriented concept
• Defined interest in helping a target population
• Willingness to develop a formal project structure

Priority Development Areas:
• Formalize the mission and service model
• Define legal/organizational structure
• Develop an operating and project budget
• Establish governance and evaluation practices

Recommended Next Step:
Proceed to Grant Readiness after converting the idea into a documented organization/project profile.`;

function status(message, kind = "") {
  const box = $("runStatus");
  if (!box) return;
  box.textContent = message;
  box.className = "statusbox " + kind;
}

function setRunButtonProcessing(isProcessing) {
  const button = $("runBtn");
  if (!button) return;

  button.disabled = isProcessing;
  button.textContent = isProcessing
    ? "Module 01 Processing…"
    : "Run Module 01";
}

function showReport(reportText) {
  const report = $("report");
  if (!report) return;

  report.textContent =
    reportText ||
    "Module 01 completed, but no report text was returned.";
}

function elapsedMessage() {
  if (!processingStartedAt) return "";

  const elapsedSeconds = Math.floor(
    (Date.now() - processingStartedAt) / 1000
  );

  if (elapsedSeconds < 60) {
    return "Analysis has started.";
  }

  const minutes = Math.floor(elapsedSeconds / 60);

  return minutes === 1
    ? "Analysis has been running for about 1 minute."
    : `Analysis has been running for about ${minutes} minutes.`;
}

function showProcessingStatus() {
  status(
    "Analyzing your organization…\n\n" +
      "✓ Your Module 00 information has been retrieved.\n" +
      "✓ Secure AI analysis has started.\n" +
      "⏳ Your Organization Intelligence Report is being prepared.\n\n" +
      elapsedMessage() +
      "\n\nThis analysis may take several minutes. " +
      "You may leave this page and return later. " +
      "Your results will be saved automatically.",
    "processing"
  );

  setRunButtonProcessing(true);
}

async function getModule01Result() {
  if (!project) return null;

  const { data, error } = await giSupabase
    .from("module_results")
    .select("*")
    .eq("project_id", project.id)
    .eq("module_number", 1)
    .maybeSingle();

  if (error) throw error;
  return data;
}

function getSavedError(moduleResult) {
  const output = moduleResult?.output_data || {};

  if (output.background_error) {
    return output.background_error;
  }

  if (output.dify_error) {
    return output.dify_error;
  }

  if (output.dify_http_error) {
    if (typeof output.dify_http_error === "string") {
      return output.dify_http_error;
    }

    return JSON.stringify(output.dify_http_error);
  }

  return "Module 01 could not be completed.";
}

function stopPolling() {
  if (pollTimer) {
    clearInterval(pollTimer);
    pollTimer = null;
  }
}

async function checkModule01Status() {
  try {
    const result = await getModule01Result();

    if (!result) return;

    if (result.status === "running") {
      if (!processingStartedAt && result.started_at) {
        processingStartedAt =
          new Date(result.started_at).getTime();
      }

      showProcessingStatus();
      return;
    }

    if (result.status === "completed") {
      stopPolling();
      setRunButtonProcessing(false);
      showReport(result.report_text);

      status(
        "✓ Module 01 complete.\n\n" +
          "Your Organization Intelligence Report has been generated and saved to your Grant Intelligence account.",
        "ok"
      );

      return;
    }

    if (result.status === "failed") {
      stopPolling();
      setRunButtonProcessing(false);

      const message = getSavedError(result);

      status(
        "Module 01 could not be completed.\n\n" +
          message +
          "\n\nYour Module 00 information is still safely stored. You may try again after the issue is corrected.",
        "bad"
      );
    }
  } catch (error) {
    console.error(
      "Module 01 status check failed:",
      error
    );
    // Keep polling. A single failed status check should not stop the AI job.
  }
}

function startPolling() {
  stopPolling();

  checkModule01Status();

  pollTimer = setInterval(
    checkModule01Status,
    10000
  );
}

async function load() {
  session = await GI.requireSession("module01.html");
  if (!session) return;

  profile = await GI.getProfile();

  if (
    !profile ||
    !["demo", "realtest", "paid", "admin"].includes(
      profile.access_level
    )
  ) {
    location.replace("unlock.html");
    return;
  }

  $("modePill").textContent =
    profile.access_level === "demo"
      ? "DEMO • NO DIFY"
      : profile.access_level === "realtest"
      ? "REAL TEST • DIFY"
      : profile.access_level === "paid"
      ? "PAID • DIFY"
      : "ADMIN";

  const projectId = localStorage.getItem(
    "giCurrentProjectId"
  );

  if (!projectId) {
    $("projectInfo").textContent =
      "No current project. Complete Module 00 first.";
    $("runBtn").disabled = true;
    return;
  }

  const { data, error } = await giSupabase
    .from("projects")
    .select("*")
    .eq("id", projectId)
    .single();

  if (error) throw error;

  project = data;

  $("projectInfo").innerHTML =
    `<strong>${project.project_name}</strong><br>` +
    `${project.organization_name || "No organization name yet"}<br>` +
    `Stage: ${project.project_stage || "Not Found"}<br>` +
    `Readiness: ${project.readiness_score ?? "Not Found"}`;

  const existing = await getModule01Result();

  if (
    existing?.status === "completed" &&
    existing?.report_text
  ) {
    showReport(existing.report_text);

    status(
      "✓ A saved Module 01 report was loaded from Supabase.",
      "ok"
    );

    setRunButtonProcessing(false);
    return;
  }

  if (existing?.status === "running") {
    processingStartedAt = existing.started_at
      ? new Date(existing.started_at).getTime()
      : Date.now();

    showProcessingStatus();
    startPolling();
    return;
  }

  if (existing?.status === "failed") {
    const message = getSavedError(existing);

    status(
      "The previous Module 01 attempt did not complete.\n\n" +
        message +
        "\n\nYour Module 00 information is still saved. You may run Module 01 again.",
      "bad"
    );

    setRunButtonProcessing(false);
    return;
  }

  status(
    "Ready to generate your Organization Intelligence Report."
  );

  setRunButtonProcessing(false);
}

async function runModule01() {
  try {
    if (!project) return;

    setRunButtonProcessing(true);

    if (profile.access_level === "demo") {
      status(
        "Demo mode: loading sample report. No Dify credits are used."
      );

      const { error } = await giSupabase
        .from("module_results")
        .upsert(
          {
            user_id: session.user.id,
            project_id: project.id,
            module_number: 1,
            module_name: "Organization Intelligence",
            status: "completed",
            report_text: DEMO_REPORT,
            output_data: {
              sample: true,
              source: "static_demo"
            },
            completed_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            onConflict: "project_id,module_number"
          }
        );

      if (error) throw error;

      showReport(DEMO_REPORT);

      status(
        "✓ Demo Module 01 completed and saved to Supabase. Dify was not called.",
        "ok"
      );

      setRunButtonProcessing(false);
      return;
    }

    processingStartedAt = Date.now();
    showProcessingStatus();

    const { data, error } =
      await giSupabase.functions.invoke(
        "run-module01",
        {
          body: {
            project_id: project.id
          }
        }
      );

    if (error) throw error;

    if (data?.error) {
      throw new Error(data.error);
    }

    if (data?.status === "running") {
      showProcessingStatus();
      startPolling();
      return;
    }

    throw new Error(
      "Module 01 did not return a valid processing status."
    );
  } catch (error) {
    console.error(
      "Module 01 launcher error:",
      error
    );

    stopPolling();
    setRunButtonProcessing(false);

    status(
      "Unable to start Module 01: " +
        (error?.message || String(error)),
      "bad"
    );
  }
}

function attachModule01Events() {
  const button = $("runBtn");

  if (!button) {
    console.error(
      "Run Module 01 button was not found."
    );
    return;
  }

  button.addEventListener(
    "click",
    runModule01
  );
}

document.addEventListener(
  "DOMContentLoaded",
  async () => {
    try {
      attachModule01Events();
      await load();
    } catch (error) {
      console.error(
        "Unable to load Module 01:",
        error
      );

      status(
        "Unable to load Module 01: " +
          (error?.message || String(error)),
        "bad"
      );
    }
  }
);

window.addEventListener(
  "beforeunload",
  () => {
    stopPolling();
  }
);
