const $=id=>document.getElementById(id);
let session=null,profile=null,project=null;

const DEMO_REPORT=`# GRANT INTELLIGENCE™

## Module 01 – Organization Intelligence (DEMO SAMPLE)

This is demonstration content. It was not generated by Dify and does not describe the signed-in user.

Organization Stage: Planning
Mission Clarity: Developing
Program Definition: Preliminary
Governance: Development Required
Financial Infrastructure: Development Required

Key Strengths:
• Clear community-oriented concept
• Defined interest in helping a target population
• Willingness to develop a formal project structure

Priority Development Areas:
• Formalize the mission and service model
• Define legal/organizational structure
• Develop an operating and project budget
• Establish governance and evaluation practices

Recommended Next Step:
Proceed to Grant Readiness after converting the idea into a documented organization/project profile.`;

function status(msg,kind=''){
  $('runStatus').textContent=msg;
  $('runStatus').className='statusbox '+kind;
}

async function load(){
  session=await GI.requireSession('module01.html');
  if(!session)return;
  profile=await GI.getProfile();
  if(!profile || !['demo','realtest','paid','admin'].includes(profile.access_level)){
    location.replace('unlock.html');return;
  }
  $('modePill').textContent=
    profile.access_level==='demo'?'DEMO • NO DIFY':
    profile.access_level==='realtest'?'REAL TEST • DIFY':
    profile.access_level==='paid'?'PAID • DIFY':'ADMIN';

  const projectId=localStorage.getItem('giCurrentProjectId');
  if(!projectId){
    $('projectInfo').textContent='No current project. Complete Module 00 first.';
    $('runBtn').disabled=true;return;
  }
  const {data,error}=await giSupabase.from('projects').select('*').eq('id',projectId).single();
  if(error)throw error;
  project=data;
  $('projectInfo').innerHTML=`<strong>${project.project_name}</strong><br>${project.organization_name||'No organization name yet'}<br>Stage: ${project.project_stage||'Not Found'}<br>Readiness: ${project.readiness_score??'Not Found'}`;

  const {data:existing}=await giSupabase.from('module_results')
    .select('*').eq('project_id',project.id).eq('module_number',1).maybeSingle();
  if(existing?.status==='completed' && existing.report_text){
    $('report').textContent=existing.report_text;
    status('A saved Module 01 report was loaded from Supabase.','ok');
  }
}

$('runBtn').addEventListener('click',async()=>{
  try{
    if(!project)return;
    $('runBtn').disabled=true;
    if(profile.access_level==='demo'){
      status('Demo mode: loading sample report. No Dify credits are used.');
      const {error}=await giSupabase.from('module_results').upsert({
        user_id:session.user.id,
        project_id:project.id,
        module_number:1,
        module_name:'Organization Intelligence',
        status:'completed',
        report_text:DEMO_REPORT,
        output_data:{sample:true,source:'static_demo'},
        completed_at:new Date().toISOString(),
        updated_at:new Date().toISOString()
      },{onConflict:'project_id,module_number'});
      if(error)throw error;
      $('report').textContent=DEMO_REPORT;
      status('Demo Module 01 completed and saved to Supabase. Dify was not called.','ok');
      return;
    }

    status('Calling secure Supabase → Dify Module 01 bridge…');
    const {data,error}=await giSupabase.functions.invoke('run-module01',{
      body:{project_id:project.id}
    });
    if(error)throw error;
    if(data?.error)throw new Error(data.error+(data?.dify?` — ${JSON.stringify(data.dify)}`:''));
    const report=data?.module_result?.report_text || 'Module 01 completed, but no report text was returned.';
    $('report').textContent=report;
    status('Module 01 completed in Dify and the result was saved to Supabase.','ok');
  }catch(err){
    console.error(err);
    status('Module 01 failed: '+(err.message||err),'bad');
  }finally{
    $('runBtn').disabled=false;
  }
});

load().catch(err=>status('Unable to load Module 01: '+err.message,'bad'));
