const questions = [
  {c:'Foundation',q:'How far along are you right now?',a:[['I only have an idea',0],['I have notes or a rough concept',1],['I have a mission or project description',2],['I already operate a business, nonprofit, or program',4]]},
  {c:'Foundation',q:'Do you have a clear mission or purpose statement?',a:[['No',0],['I know it in my head',1],['I have a rough draft',2],['Yes, it is written and clear',4]]},
  {c:'Foundation',q:'Have you identified the main problem or need you want to address?',a:[['Not yet',0],['Generally',1],['Yes, but it needs detail',2],['Yes, clearly',4]]},
  {c:'Foundation',q:'Do you know who you want to help?',a:[['Not yet',0],['Broadly',1],['Mostly',2],['Yes, clearly defined',4]]},
  {c:'Governance',q:'Do you currently have a legal organization or formal structure?',a:[['No',0],['Considering options',1],['In progress',2],['Yes',4]]},
  {c:'Governance',q:'Do you have people who can help lead or advise the project?',a:[['No',0],['Maybe',1],['A few informal supporters',2],['Yes, a defined team or board',4]]},
  {c:'Governance',q:'Do you have basic policies, responsibilities, or decision-making roles documented?',a:[['No',0],['Not yet, but planned',1],['Some',2],['Yes',4]]},
  {c:'Financial',q:'Do you have an annual operating budget or personal project budget?',a:[['No',0],['I have rough estimates',1],['Partial budget',2],['Yes, documented',4]]},
  {c:'Financial',q:'Do you have a budget for the specific idea or project you want funded?',a:[['No',0],['Rough estimate only',1],['Draft budget',2],['Yes, detailed',4]]},
  {c:'Financial',q:'Can you document income, expenses, or financial activity if asked?',a:[['No',0],['Very limited',1],['Some records',2],['Yes, organized records',4]]},
  {c:'Financial',q:'Do you have a consistent way to track money and expenses?',a:[['No',0],['Occasionally',1],['Basic spreadsheet or app',2],['Yes, consistent system',4]]},
  {c:'Program',q:'Can you describe what you would actually do with grant funding?',a:[['Not yet',0],['I have a general idea',1],['Mostly',2],['Yes, clearly',4]]},
  {c:'Program',q:'Have you identified specific activities, services, or deliverables?',a:[['No',0],['A few ideas',1],['Some are defined',2],['Yes',4]]},
  {c:'Program',q:'Do you know what successful results would look like?',a:[['No',0],['Generally',1],['Some outcomes are clear',2],['Yes, measurable outcomes are defined',4]]},
  {c:'Program',q:'Can you explain why this project matters to the people or community you want to serve?',a:[['Not yet',0],['Generally',1],['Yes, but I need evidence',2],['Yes, with supporting evidence',4]]},
  {c:'Grant Capacity',q:'Have you or your organization ever applied for a grant?',a:[['Never',0],['I have researched grants',1],['Applied once or twice',2],['Yes, multiple applications',4]]},
  {c:'Grant Capacity',q:'Do you have documents that could support a grant application?',a:[['None yet',0],['A few informal documents',1],['Several useful documents',2],['Yes, a strong document set',4]]},
  {c:'Planning',q:'Do you have a written plan for what you want to accomplish over the next 1–3 years?',a:[['No',0],['Only ideas',1],['A rough plan',2],['Yes, documented',4]]}
];
let i=0, answers=Array(questions.length).fill(null);
const $=id=>document.getElementById(id);
$('startAssessment').onclick=()=>{$('assessmentIntro').style.display='none';$('assessmentPanel').style.display='block';render()};
function render(){const x=questions[i];$('questionCount').textContent=`Question ${i+1} of ${questions.length}`;$('progressPct').textContent=`${Math.round((i+1)/questions.length*100)}%`;$('progressBar').style.width=`${(i+1)/questions.length*100}%`;$('questionCategory').textContent=x.c;$('questionTitle').textContent=x.q;$('choices').innerHTML='';x.a.forEach(([label,val],idx)=>{const d=document.createElement('label');d.className='choice'+(answers[i]===idx?' selected':'');d.innerHTML=`<input type="radio" name="choice" ${answers[i]===idx?'checked':''}> <span>${label}</span>`;d.onclick=()=>{answers[i]=idx;render()};$('choices').appendChild(d)});$('prevBtn').disabled=i===0;$('nextBtn').textContent=i===questions.length-1?'See My Score':'Next'}
$('prevBtn').onclick=()=>{if(i>0){i--;render()}};
$('nextBtn').onclick=()=>{if(answers[i]===null){alert('Choose the answer that best describes where you are today.');return}if(i<questions.length-1){i++;render()}else showResults()};
function showResults(){let total=0,max=questions.length*4;const cat={};questions.forEach((q,idx)=>{const val=q.a[answers[idx]][1];total+=val;cat[q.c]??={got:0,max:0};cat[q.c].got+=val;cat[q.c].max+=4});const score=Math.round(total/max*100);localStorage.setItem('giLatestScore',score);const hist=JSON.parse(localStorage.getItem('giScoreHistory')||'[]');hist.push({score,date:new Date().toLocaleDateString()});localStorage.setItem('giScoreHistory',JSON.stringify(hist.slice(-6)));$('assessmentPanel').style.display='none';$('resultsPanel').classList.add('active');$('finalScore').textContent=score;$('readinessLabel').textContent=score<25?'Idea Stage — Strong Starting Point':score<50?'Foundation Building':score<70?'Developing Readiness':score<85?'Nearly Grant Ready':'Grant Ready Foundation';$('categoryGrid').innerHTML='';Object.entries(cat).forEach(([name,v])=>{const pct=Math.round(v.got/v.max*100);$('categoryGrid').innerHTML+=`<div class="category"><div class="category-head"><span>${name}</span><span>${pct}%</span></div><div class="bar"><span style="width:${pct}%"></span></div></div>`});const recs=[];if(score<25)recs.push('Turn your idea into a one-page mission and project concept.','Define exactly who you want to help and what problem you want to solve.');if(score<50)recs.push('Document your project activities, desired outcomes, and basic budget assumptions.');if(score<70)recs.push('Strengthen financial records, governance, and measurable outcomes.');if(score>=70)recs.push('Focus on funder matching, evidence, proposal requirements, and submission readiness.');if(score<85)recs.push('Use the paid Grant Intelligence process to identify what you already have and what is still missing.');$('recommendations').innerHTML=recs.map(r=>`<div class="rec">${r}</div>`).join('');const prev=hist.length>1?hist[hist.length-2].score:null;$('historyBox').innerHTML=prev===null?`This is your first recorded assessment on this device. Retake it after completing planning work to measure progress.`:`Previous score: <strong>${prev}</strong> &nbsp;→&nbsp; Current score: <strong>${score}</strong> &nbsp; (${score-prev>=0?'+':''}${score-prev} points)`;window.scrollTo({top:0,behavior:'smooth'})}
$('retakeBtn').onclick=()=>{i=0;answers=Array(questions.length).fill(null);$('resultsPanel').classList.remove('active');$('assessmentPanel').style.display='block';render();window.scrollTo({top:0,behavior:'smooth'})};
